---
name: release

# This workflow requires a PYPI_API_TOKEN secret to be defined in the GitHub
# repository settings.

on:
  push:
    tags: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set package version in setup.cfg
        run: sed -i "s/^version = 0$/version = ${GITHUB_REF_NAME#v}/" setup.cfg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          python -m twine upload dist/*
